Update Grocery_List_CRC_이승준.txt
fishinSausage/iikh_2024 pull request #12
Opened 2024-10-03 10:01 UTC by lsjs0706

arrow key로 셀렉하는 부분 빼고 refine 했습니다.
수정사항 밑에 달아주시면 보고 수정하도록 하겠습니다.

2024-10-03 23:06 UTC, fishinSausage requested changes

2024-10-03 23:06 UTC, fishinSausage commented on CRC/Grocery_List_CRC_이승준.txt
1.메소드들 인수랑 반환형 정확하게 명시해주세요
2.메뉴도 같이 받으면 좋겠다고 생각하는데, 이건  어디까지나 제  의견이니까 동의하시지 않으시면 무시하셔도 좋습니다
3.name을 단순히 변수로 하는게 아니라, 배열 해야하지 않을까요? 정확하게 명시해주세요 - 만약 배열로 한다면, 유형별로 unit이 다르므로(ex: 간장 - tbsp / 소고기 - g / 후추 - 10번 grind ) 이것에 대해 명시하면 좋겠습니다
4. 혹시 grocery list의 인스턴스를 계속 만들어서 각각에 아이템을 넣으실 생각이신가요? 아니면 하나의 인스턴스에 배열로 전부 다 집어넣으실 생각이신가요? - 만약 전자일 경우에는, 어쨌든 다른 클래스에서는 grocery list를 print하는 인터페이스가 필요할 것이므로, 하나의 manager class가 존재하여 걔가 인터페이스를 담당하도록 하는것이 좋다고 생각되네요. 아니면 후자로 하셔도 되고요

2024-10-04 06:35 UTC, lsjs0706 commented on CRC/Grocery_List_CRC_이승준.txt
1. 네 수정하겠습니다.
2. 메뉴도 같이 받는게 좋을 것 같네요. Greeter 클래스 구현에서 switch로 나눠서 함수 실행하도록 해놓긴 했는데, 메뉴로 같이 받는게 훨씬 효율적이라 생각합니다. 추가하도록 하겠습니다.
3. 이름을 배열로 해야될 필요성을 잘 못느끼겠습니다. 어떤 이유로 배열로 구현하셨으면 좋겠는지 설명해주시면 감사하겠습니다.
 그렇게 생각하는 이유는 각 grocery item의 객체들은 고유한 이름을 가지기 때문에, 배열로 구현했을 경우, 여러개의 아이템들이 배열에 동시에 저장되어 여러개의 이름을 가지게 되고, Grocery List로 관리하기 더 힘들어질 것 같네요.
unit의 경우 사용자에게 단위를 제한하는 정도로 운영하면 될 것 같다고 생각합니다. (예시 : tbsp, g, ml, grind)
4. Grocery List 하나의 객체에 배열로 모든 아이템을 운영할 계획입니다.

2024-10-06 09:25 UTC, fishinSausage approved these changes
메인에 머지했습니다. 하지만 조금 더 수정해주세요

2024-10-06 09:25 UTC, merged