update Meal_CRC_엄윤상.txt
fishinSausage/iikh_2024 pull request #8
Opened 2024-10-03 08:17 UTC by bambbdd

line 8:  #?should the display of a recipe change according to serving size?#
이 부분은 어떻게 메서드를 짜야 할지 감이 잘 안잡히기도 하고 좀 복잡해질 것 같아서 제외했습니다.

line 10:#?if recipe is selected and edited -> it has to be updated in the meal too : done by using pointers?#
DB에 포인터로 접근할 예정이기에 DB의 레시피가 바뀐다면 자동으로 내용이 변경될 것 같습니다.

2024-10-03 08:57 UTC, fishinSausage requested changes

2024-10-03 08:57 UTC, fishinSausage commented on CRC/Meal_CRC_엄윤상.txt
1. responsibility를 메소드로 구현한 것이므로 responsibility 다 지워주세요
2. 하나의 display 함수만 있어도 충분할 것 같습니다
3. delete 함수 수정할 필요가 있어보입니다 : 제가 생각한 것 : display 로 listing -> arrow key 와 enter를 통해 select(추가함수) -> 이후 recipe로 control이 넘어가 그 안에서 삭제  - 만약 다른 생각을 가지고 계신거라면 3번은 무시하셔도 좋습니다.
4. 내부의 state들을 위해서 getter 와 setter를 설명해주신건가요? - 그렇다면 저거 대신, state를 명시해주시면 좋겠습니다 - 또한 Date 인스턴스 안에 여러 Meal 인스턴스가 들어있는 형식인데, Meal 인스턴스 안에서 Date 변수가 필요할지 잘 모르겠네요

2024-10-03 12:57 UTC, bambbdd commented on CRC/Meal_CRC_엄윤상.txt
1. 완료했습니다.
2, 3. display는 단순하게 클래스 정보를 찍는 메서드입니다. / delete를 호출하면 레시피들만 display되고 그중에서 arrow keys를 통해 레시피를 삭제하려고 합니다.
4. States: 항목을 추가해 정리하였습니다. 말씀하신대로 Date 변수는 필요 없을 것 같습니다.

2024-10-03 12:58 UTC, bambbdd commented
1. 완료했습니다.
2, 3. display는 단순하게 클래스 정보를 찍는 메서드입니다. / delete를 호출하면 레시피들만 display되고 그중에서 arrow keys를 통해 레시피를 삭제하려고 합니다.
4. States: 항목을 추가해 정리하였습니다. 말씀하신대로 Date 변수는 필요 없을 것 같습니다.

2024-10-03 13:07 UTC, bambbdd commented
.idea 폴더 커밋에서 제거하였습니다.

2024-10-03 23:26 UTC, fishinSausage commented on CRC/Meal_CRC_엄윤상.txt
1.add 안에서 browse 와 serach 가 아직 필요하므로 responsibility에 놔두겠습니다
2.프린터기에 인쇄하는 것도 놔두겠습니다.
3.delete 를 이 클래스에서 구현하는 것보단, display 함수 안에서 레시피 클래스 자체의 display,edit,delete 메소드를 사용하는게 좋아보이네요 - 근데 제 생각이니까 이부분은 그냥 두겠습니다
4.sort가 없어도 된다고 생각하네요.
애매한 부분 ? 추가하고 머지하겠습니다. 코드작성 시작하셔도 좋을거 같습니다,  대신 제가 언급드린 부분이나 아니면 스스로 인터페이스 바꾸신다면 여기에도 수정하고 pull request 해주세요

2024-10-03 23:31 UTC, merged

2024-10-04 15:38 UTC, bambbdd commented
1. display 메서드에서 display 이후에 arrow keys로 recipe 이외의 다른 것을 골랐을 때 수정할 수 있도록 하고,
recipe를 골랐을 때에는 edit하거나 remove(delete)할 수 있도록 하였습니다.
2. addRecipe() 또한 매개변수를 받아 추가하는 것이 아닌 Recipe DB에서 arrow keys로 browse하여 추가할 수 있도록 하였습니다.
3. 단순하게 Meal의 정보를 찍어낼 수 있는 print 메서드를 추가하였습니다.
4. sort는 삭제하였습니다.